import { fetchAllPosts } from '@/src/api/api'
import Article from '@/src/components/Article/Article'
import Search from '@/src/components/Search/Search'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import React, { ReactElement } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ posts }: { posts:  Record<string, any>[] }) : ReactElement {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Search />
        <div className={styles.articles}>
          {posts.map((post: Record<string, any>, index: number) => (
              <Article key={index} post={post} />
          ))}
          
        </div>
    </>
  )
}

export const getStaticProps = async () => {
  const posts = await fetchAllPosts(10, 1)
  return {
    props: {
      posts
    }
  }
}
